# Generated by Django 4.2.10 on 2026-04-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_update_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
